- name: Find patches for Windows
  hosts: windows
  tasks:
    - name: Use Windows Update to find updates for the default group
      ansible.windows.win_updates:
        state: searched
        category_names: '*'
        server_selection: windows_update
      register: patch_results

    - name: Print the available patches
      ansible.builtin.debug:
        var: patch_results 
