- name: Find, download and apply patches for Windows
  hosts: windows
  tasks:      
    - name: Apply any patches and reboot as needed
      ansible.windows.win_updates:
        category_names: '*'
        state: installed
        reboot: true
    
